// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package withdraw

import (
	"server/api/withdraw"
)

type ControllerV1 struct{}

func NewV1() withdraw.IWithdrawV1 {
	return &ControllerV1{}
}
