// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package distribute

import (
	"server/api/distribute"
)

type ControllerV1 struct{}

func NewV1() distribute.IDistributeV1 {
	return &ControllerV1{}
}
