// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProductSpecAttrsDao is an internal type for wrapping the internal DAO implementation.
type internalSysProductSpecAttrsDao = *internal.SysProductSpecAttrsDao

// sysProductSpecAttrsDao is the data access object for the table sys_product_spec_attrs.
// You can define custom methods on it to extend its functionality as needed.
type sysProductSpecAttrsDao struct {
	internalSysProductSpecAttrsDao
}

var (
	// SysProductSpecAttrs is a globally accessible object for table sys_product_spec_attrs operations.
	SysProductSpecAttrs = sysProductSpecAttrsDao{
		internal.NewSysProductSpecAttrsDao(),
	}
)

// Add your custom methods and functionality below.
