// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysDistributeDao is an internal type for wrapping the internal DAO implementation.
type internalSysDistributeDao = *internal.SysDistributeDao

// sysDistributeDao is the data access object for the table sys_distribute.
// You can define custom methods on it to extend its functionality as needed.
type sysDistributeDao struct {
	internalSysDistributeDao
}

var (
	// SysDistribute is a globally accessible object for table sys_distribute operations.
	SysDistribute = sysDistributeDao{
		internal.NewSysDistributeDao(),
	}
)

// Add your custom methods and functionality below.
