// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysLevelDao is an internal type for wrapping the internal DAO implementation.
type internalSysLevelDao = *internal.SysLevelDao

// sysLevelDao is the data access object for the table sys_level.
// You can define custom methods on it to extend its functionality as needed.
type sysLevelDao struct {
	internalSysLevelDao
}

var (
	// SysLevel is a globally accessible object for table sys_level operations.
	SysLevel = sysLevelDao{
		internal.NewSysLevelDao(),
	}
)

// Add your custom methods and functionality below.
