// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProductSpecValuesDao is an internal type for wrapping the internal DAO implementation.
type internalSysProductSpecValuesDao = *internal.SysProductSpecValuesDao

// sysProductSpecValuesDao is the data access object for the table sys_product_spec_values.
// You can define custom methods on it to extend its functionality as needed.
type sysProductSpecValuesDao struct {
	internalSysProductSpecValuesDao
}

var (
	// SysProductSpecValues is a globally accessible object for table sys_product_spec_values operations.
	SysProductSpecValues = sysProductSpecValuesDao{
		internal.NewSysProductSpecValuesDao(),
	}
)

// Add your custom methods and functionality below.
