// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysVipDao is an internal type for wrapping the internal DAO implementation.
type internalSysVipDao = *internal.SysVipDao

// sysVipDao is the data access object for the table sys_vip.
// You can define custom methods on it to extend its functionality as needed.
type sysVipDao struct {
	internalSysVipDao
}

var (
	// SysVip is a globally accessible object for table sys_vip operations.
	SysVip = sysVipDao{
		internal.NewSysVipDao(),
	}
)

// Add your custom methods and functionality below.
