// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysWitkeyOnboardingDao is an internal type for wrapping the internal DAO implementation.
type internalSysWitkeyOnboardingDao = *internal.SysWitkeyOnboardingDao

// sysWitkeyOnboardingDao is the data access object for the table sys_witkey_onboarding.
// You can define custom methods on it to extend its functionality as needed.
type sysWitkeyOnboardingDao struct {
	internalSysWitkeyOnboardingDao
}

var (
	// SysWitkeyOnboarding is a globally accessible object for table sys_witkey_onboarding operations.
	SysWitkeyOnboarding = sysWitkeyOnboardingDao{
		internal.NewSysWitkeyOnboardingDao(),
	}
)

// Add your custom methods and functionality below.
