// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysGameDao is an internal type for wrapping the internal DAO implementation.
type internalSysGameDao = *internal.SysGameDao

// sysGameDao is the data access object for the table sys_game.
// You can define custom methods on it to extend its functionality as needed.
type sysGameDao struct {
	internalSysGameDao
}

var (
	// SysGame is a globally accessible object for table sys_game operations.
	SysGame = sysGameDao{
		internal.NewSysGameDao(),
	}
)

// Add your custom methods and functionality below.
