// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysCommentDao is an internal type for wrapping the internal DAO implementation.
type internalSysCommentDao = *internal.SysCommentDao

// sysCommentDao is the data access object for the table sys_comment.
// You can define custom methods on it to extend its functionality as needed.
type sysCommentDao struct {
	internalSysCommentDao
}

var (
	// SysComment is a globally accessible object for table sys_comment operations.
	SysComment = sysCommentDao{
		internal.NewSysCommentDao(),
	}
)

// Add your custom methods and functionality below.
