// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysUserCardDao is an internal type for wrapping the internal DAO implementation.
type internalSysUserCardDao = *internal.SysUserCardDao

// sysUserCardDao is the data access object for the table sys_user_card.
// You can define custom methods on it to extend its functionality as needed.
type sysUserCardDao struct {
	internalSysUserCardDao
}

var (
	// SysUserCard is a globally accessible object for table sys_user_card operations.
	SysUserCard = sysUserCardDao{
		internal.NewSysUserCardDao(),
	}
)

// Add your custom methods and functionality below.
