// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysPunishDao is an internal type for wrapping the internal DAO implementation.
type internalSysPunishDao = *internal.SysPunishDao

// sysPunishDao is the data access object for the table sys_punish.
// You can define custom methods on it to extend its functionality as needed.
type sysPunishDao struct {
	internalSysPunishDao
}

var (
	// SysPunish is a globally accessible object for table sys_punish operations.
	SysPunish = sysPunishDao{
		internal.NewSysPunishDao(),
	}
)

// Add your custom methods and functionality below.
