// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProductSkuDao is an internal type for wrapping the internal DAO implementation.
type internalSysProductSkuDao = *internal.SysProductSkuDao

// sysProductSkuDao is the data access object for the table sys_product_sku.
// You can define custom methods on it to extend its functionality as needed.
type sysProductSkuDao struct {
	internalSysProductSkuDao
}

var (
	// SysProductSku is a globally accessible object for table sys_product_sku operations.
	SysProductSku = sysProductSkuDao{
		internal.NewSysProductSkuDao(),
	}
)

// Add your custom methods and functionality below.
