// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProductDao is an internal type for wrapping the internal DAO implementation.
type internalSysProductDao = *internal.SysProductDao

// sysProductDao is the data access object for the table sys_product.
// You can define custom methods on it to extend its functionality as needed.
type sysProductDao struct {
	internalSysProductDao
}

var (
	// SysProduct is a globally accessible object for table sys_product operations.
	SysProduct = sysProductDao{
		internal.NewSysProductDao(),
	}
)

// Add your custom methods and functionality below.
