// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysRechargeDao is an internal type for wrapping the internal DAO implementation.
type internalSysRechargeDao = *internal.SysRechargeDao

// sysRechargeDao is the data access object for the table sys_recharge.
// You can define custom methods on it to extend its functionality as needed.
type sysRechargeDao struct {
	internalSysRechargeDao
}

var (
	// SysRecharge is a globally accessible object for table sys_recharge operations.
	SysRecharge = sysRechargeDao{
		internal.NewSysRechargeDao(),
	}
)

// Add your custom methods and functionality below.
