// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProductSkuSpecRelationsDao is an internal type for wrapping the internal DAO implementation.
type internalSysProductSkuSpecRelationsDao = *internal.SysProductSkuSpecRelationsDao

// sysProductSkuSpecRelationsDao is the data access object for the table sys_product_sku_spec_relations.
// You can define custom methods on it to extend its functionality as needed.
type sysProductSkuSpecRelationsDao struct {
	internalSysProductSkuSpecRelationsDao
}

var (
	// SysProductSkuSpecRelations is a globally accessible object for table sys_product_sku_spec_relations operations.
	SysProductSkuSpecRelations = sysProductSkuSpecRelationsDao{
		internal.NewSysProductSkuSpecRelationsDao(),
	}
)

// Add your custom methods and functionality below.
