// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysWitkeyDao is an internal type for wrapping the internal DAO implementation.
type internalSysWitkeyDao = *internal.SysWitkeyDao

// sysWitkeyDao is the data access object for the table sys_witkey.
// You can define custom methods on it to extend its functionality as needed.
type sysWitkeyDao struct {
	internalSysWitkeyDao
}

var (
	// SysWitkey is a globally accessible object for table sys_witkey operations.
	SysWitkey = sysWitkeyDao{
		internal.NewSysWitkeyDao(),
	}
)

// Add your custom methods and functionality below.
