// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProfitDao is an internal type for wrapping the internal DAO implementation.
type internalSysProfitDao = *internal.SysProfitDao

// sysProfitDao is the data access object for the table sys_profit.
// You can define custom methods on it to extend its functionality as needed.
type sysProfitDao struct {
	internalSysProfitDao
}

var (
	// SysProfit is a globally accessible object for table sys_profit operations.
	SysProfit = sysProfitDao{
		internal.NewSysProfitDao(),
	}
)

// Add your custom methods and functionality below.
