// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysCredentialDao is an internal type for wrapping the internal DAO implementation.
type internalSysCredentialDao = *internal.SysCredentialDao

// sysCredentialDao is the data access object for the table sys_credential.
// You can define custom methods on it to extend its functionality as needed.
type sysCredentialDao struct {
	internalSysCredentialDao
}

var (
	// SysCredential is a globally accessible object for table sys_credential operations.
	SysCredential = sysCredentialDao{
		internal.NewSysCredentialDao(),
	}
)

// Add your custom methods and functionality below.
